'use strict';

module.exports = {
  apps: [
    {
      name: 'erp-api-gateway',
      cwd: './services/api-gateway',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      wait_ready: false,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'api-gateway' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'api-gateway' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-auth-service',
      cwd: './services/auth-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'auth-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'auth-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-auth-worker',
      cwd: './services/auth-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'auth-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'auth-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-role-service',
      cwd: './services/role-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'role-service' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'role-service' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-user-service',
      cwd: './services/user-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'user-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'user-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-user-worker',
      cwd: './services/user-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 20000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'user-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'user-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-audit-service',
      cwd: './services/audit-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'audit-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'audit-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-audit-worker',
      cwd: './services/audit-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 20000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'audit-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'audit-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-file-service',
      cwd: './services/file-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'file-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'file-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-file-worker',
      cwd: './services/file-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 20000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'file-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'file-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-master-service',
      cwd: './services/master-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'master-service' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'master-service' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-supplier-service',
      cwd: './services/supplier-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'supplier-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'supplier-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-supplier-worker',
      cwd: './services/supplier-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'supplier-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'supplier-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-crm-service',
      cwd: './services/crm-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'crm-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'crm-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-crm-worker',
      cwd: './services/crm-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'crm-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'crm-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-rfq-service',
      cwd: './services/rfq-service',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'rfq-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'rfq-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-rfq-worker',
      cwd: './services/rfq-service',
      script: 'src/queues/worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: true,
      ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'],
      kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'rfq-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'rfq-worker' },
      error_file: './logs/pm2-worker-error.log',
      out_file: './logs/pm2-worker-out.log',
      merge_logs: true,
      time: true
    },
    {
      name: 'erp-purchase-service', cwd: './services/purchase-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'purchase-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'purchase-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-purchase-worker', cwd: './services/purchase-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'purchase-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'purchase-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-inventory-service', cwd: './services/inventory-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'inventory-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'inventory-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-inventory-worker', cwd: './services/inventory-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'inventory-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'inventory-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-warehouse-service', cwd: './services/warehouse-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'warehouse-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'warehouse-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-warehouse-worker', cwd: './services/warehouse-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'warehouse-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'warehouse-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-quality-service', cwd: './services/quality-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'quality-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'quality-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-quality-worker', cwd: './services/quality-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'quality-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'quality-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-sales-service', cwd: './services/sales-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'sales-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'sales-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-sales-worker', cwd: './services/sales-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'sales-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'sales-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-finance-service', cwd: './services/finance-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'finance-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'finance-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-finance-worker', cwd: './services/finance-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'finance-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'finance-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-shipment-service', cwd: './services/shipment-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'shipment-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'shipment-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-shipment-worker', cwd: './services/shipment-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'shipment-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'shipment-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-notification-service', cwd: './services/notification-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'notification-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'notification-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-notification-worker', cwd: './services/notification-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 15000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'notification-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'notification-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-report-service', cwd: './services/report-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'report-service', RUN_WORKERS_INLINE: 'false' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'report-service', RUN_WORKERS_INLINE: 'false' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-report-worker', cwd: './services/report-service', script: 'src/queues/worker.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M', autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 20000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'report-worker' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'report-worker' },
      error_file: './logs/pm2-worker-error.log', out_file: './logs/pm2-worker-out.log', merge_logs: true, time: true
    },
    {
      name: 'erp-dashboard-service', cwd: './services/dashboard-service', script: 'src/server.js',
      instances: 1, exec_mode: 'fork', max_memory_restart: '512M',
      autorestart: true, watch: true, ignore_watch: ['node_modules', 'logs', 'src/generated', '.git', '*.log'], kill_timeout: 10000,
      env: { NODE_ENV: 'development', SERVICE_NAME: 'dashboard-service' },
      env_production: { NODE_ENV: 'production', SERVICE_NAME: 'dashboard-service' },
      error_file: './logs/pm2-error.log', out_file: './logs/pm2-out.log', merge_logs: true, time: true
    }
  ]
};