'use strict';

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
};

const AUTH_LOG_EVENT = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  REFRESH: 'REFRESH',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  REGISTER: 'REGISTER'
};

const REVOKE_REASON = {
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  ROTATED: 'ROTATED',
  REUSE_DETECTED: 'REUSE_DETECTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  ADMIN_REVOKED: 'ADMIN_REVOKED'
};

const OTP_PURPOSE = {
  LOGIN: 'login',
  PASSWORD_RESET: 'password_reset',
  EMAIL_VERIFY: 'email_verify'
};

const QUEUE_NAMES = {
  EMAIL: 'auth.email',
  SESSION_CLEANUP: 'auth.session-cleanup'
};

const JOB_NAMES = {
  WELCOME_EMAIL: 'welcome-email',
  OTP_EMAIL: 'otp-email',
  PASSWORD_RESET_EMAIL: 'password-reset-email',
  PASSWORD_CHANGED_EMAIL: 'password-changed-email',
  ACCOUNT_LOCKED_EMAIL: 'account-locked-email',
  PURGE_EXPIRED_SESSIONS: 'purge-expired-sessions'
};

module.exports = {
  USER_STATUS,
  AUTH_LOG_EVENT,
  REVOKE_REASON,
  OTP_PURPOSE,
  QUEUE_NAMES,
  JOB_NAMES
};
