'use strict';

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COUNTRY_HEAD: 'COUNTRY_HEAD',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE',
  PURCHASE_MANAGER: 'PURCHASE_MANAGER',
  PURCHASE_EXECUTIVE: 'PURCHASE_EXECUTIVE',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
  QUALITY_INSPECTOR: 'QUALITY_INSPECTOR',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  FINANCE_EXECUTIVE: 'FINANCE_EXECUTIVE',
  LOGISTICS_MANAGER: 'LOGISTICS_MANAGER',
  CRM_EXECUTIVE: 'CRM_EXECUTIVE',
  MANAGEMENT: 'MANAGEMENT',
  CUSTOMER_PORTAL: 'CUSTOMER_PORTAL',
  SUPPLIER_PORTAL: 'SUPPLIER_PORTAL'
};

module.exports = { ROLES, ROLE_LIST: Object.values(ROLES) };
